version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URL=mongodb://mongo:27017/e-water-gate
      - JWT_SECRET=dev-jwt-secret-key
      - JWT_EXP=24h
      - GMAIL_USER=your-gmail@gmail.com
      - GMAIL_PASS=your-gmail-app-password
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=e-water-gate
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge 