version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=Development
      - PORT=4000
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      - JWT_EXP=24h
      - GMAIL_USER=kumjude09@gmail.com
      - GMAIL_PASS="sdgv tadj owhp nopv"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge